openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/users/create:
    post:
      summary: ''
      operationId: postApiUsersCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/users/update/{id}':
    post:
      summary: ''
      operationId: postApiUsersUpdateId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: recusandae
        required: true
        schema:
          type: string
  '/api/users/delete/{id}':
    post:
      summary: ''
      operationId: postApiUsersDeleteId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the delete.'
        example: quo
        required: true
        schema:
          type: string
  /api/users/changepassword:
    post:
      summary: ''
      operationId: postApiUsersChangepassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  description: ''
                  example: non
              required:
                - password
      security: []
  /api/users/role:
    get:
      summary: ''
      operationId: getApiUsersRole
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/logout:
    post:
      summary: ''
      operationId: postApiLogout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/programmes:
    get:
      summary: ''
      operationId: getApiProgrammes
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/programmes/create:
    post:
      summary: ''
      operationId: postApiProgrammesCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/programmes/update/{id}':
    post:
      summary: ''
      operationId: postApiProgrammesUpdateId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: quasi
        required: true
        schema:
          type: string
  '/api/programmes/delete/{id}':
    post:
      summary: ''
      operationId: postApiProgrammesDeleteId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the delete.'
        example: dolore
        required: true
        schema:
          type: string
  /api/oeuvres:
    get:
      summary: ''
      operationId: getApiOeuvres
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/oeuvres/create:
    post:
      summary: ''
      operationId: postApiOeuvresCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  '/api/oeuvres/update/{id}':
    post:
      summary: ''
      operationId: postApiOeuvresUpdateId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: ratione
        required: true
        schema:
          type: string
  '/api/oeuvres/delete/{id}':
    post:
      summary: ''
      operationId: postApiOeuvresDeleteId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the delete.'
        example: quibusdam
        required: true
        schema:
          type: string
  /api/demandes:
    get:
      summary: ''
      operationId: getApiDemandes
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/demandes/create:
    post:
      summary: ''
      operationId: postApiDemandesCreate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/demandes/attachments:
    get:
      summary: ''
      operationId: getApiDemandesAttachments
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/paydemande/{id}':
    post:
      summary: ''
      operationId: postApiPaydemandeId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the paydemande.'
        example: aut
        required: true
        schema:
          type: string
  /api/file:
    get:
      summary: ''
      operationId: getApiFile
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/demandes/status/{id}':
    post:
      summary: ''
      operationId: postApiDemandesStatusId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the status.'
        example: eos
        required: true
        schema:
          type: string
  /api/stats:
    get:
      summary: ''
      operationId: getApiStats
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/programmes/count:
    get:
      summary: ''
      operationId: getApiProgrammesCount
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/annonces/count:
    get:
      summary: ''
      operationId: getApiAnnoncesCount
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/demandes/count:
    get:
      summary: ''
      operationId: getApiDemandesCount
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/transferer:
    post:
      summary: ''
      operationId: postApiTransferer
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/distribuer-budget:
    post:
      summary: ''
      operationId: postApiDistribuerBudget
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/billan:
    get:
      summary: ''
      operationId: getApiBillan
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/notification/{id}/read':
    put:
      summary: ''
      operationId: putApiNotificationIdRead
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the notification.'
        example: 1
        required: true
        schema:
          type: integer
  /api/notifications:
    get:
      summary: ''
      operationId: getApiNotifications
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/notificationcount:
    get:
      summary: ''
      operationId: getApiNotificationcount
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/login:
    post:
      summary: ''
      operationId: postApiLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: gorczany.aubrey@example.net
                password:
                  type: string
                  description: ''
                  example: qui
              required:
                - email
                - password
      security: []
tags:
  -
    name: Endpoints
    description: ''
